{% set name = "metrolopy" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57eab29af7a73de45a410f06dac15a5313f54b4e6cb3b38dd3968b0fc59fe220

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.13
    - matplotlib-base
    - pandas
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - metrolopy
    - metrolopy.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://nrc-cnrc.github.io/MetroloPy
  summary: 'tools for dealing with measured quantities: uncertainty propagation and unit conversion'
  description: |
    A pure python package with tools for handling first order and Monte-Carlo
    propagation of uncertainty; handles relative, absolute, and expanded
    uncertainties of quantities with units.
  license: GPL-3.0-only
  license_file: metrolopy/license.txt
  doc_url: https://nrc-cnrc.github.io/MetroloPy
  dev_url: https://github.com/nrc-cnrc/Metrolopy

extra:
  recipe-maintainers:
    - hvparks
