{% set name = "metrolopy" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70227108436fd0f5711148844d24f2e24c6b87e9c9a6f2c46bf4294be5d808a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - uv_build
  run:
    - numpy >=1.17.3
    - matplotlib-base >=3.1.2
    - pandas >=0.25.2
    - python >={{ python_min }}
    - scipy >=1.3.2

test:
  imports:
    - metrolopy
    - metrolopy.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://nrc-cnrc.github.io/MetroloPy
  summary: 'tools for dealing with measured quantities: uncertainty propagation and unit conversion'
  description: |
    A pure python package with tools for handling first order and Monte-Carlo
    propagation of uncertainty; handles relative, absolute, and expanded
    uncertainties of quantities with units.
  license: GPL-3.0-only
  license_file: metrolopy/license.txt
  doc_url: https://nrc-cnrc.github.io/MetroloPy
  dev_url: https://github.com/nrc-cnrc/Metrolopy

extra:
  recipe-maintainers:
    - hvparks
