{% set name = "metrolopy" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f40427004e6cd09823129f8b0d64a4a952f249d9f93744a01022eb4a816ac517
  
context:
  python_min: "3.10"
  
build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - numpy >=1.25.0
    - matplotlib-base >=3.1.2
    - pandas >=0.25.2
    - python >=${{ python_min }}
    - scipy >=1.3.2
    - ipython >=7.9.0
    - odrpack >=0.5.0
    - lazy_loader >=0.5

test:
  imports:
    - metrolopy
    - metrolopy.tests
  commands:
    - pip check
  requires:
    - pip
    - python ${{ python_min }}

about:
  home: https://nrc-cnrc.github.io/MetroloPy
  summary: 'tools for dealing with measured quantities: uncertainty propagation and unit conversion'
  description: |
    A pure python package with tools for handling first order and Monte-Carlo
    propagation of uncertainty; handles relative, absolute, and expanded
    uncertainties of quantities with units.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://nrc-cnrc.github.io/MetroloPy
  dev_url: https://github.com/nrc-cnrc/Metrolopy

extra:
  recipe-maintainers:
    - hvparks
